### ISSUE TITLE
Update Past Events Page

### ISSUE THREAD

**Issue by johnrhimawan** [NESGroundZero/groundzero-website#34]
Update the Past Events page with the following writeup:
_______________________________________________________________________________________________________________

Ground Zero has been one of the largest student led Startathons in Singapore. 

Despite the covid situation, we still managed to accumulate over 200 participants for GZ 2021. Subsequently, over 381 participants registered for the following year for GZ 2022. 

Ground Zero is filled with students from all faculties equipped with different skillsets sharing a common entrepreneurial spirit looking to make a difference. For GZ 2022, there were 31.2% from Computing, 24.1% from Business, 21.5% from Engineering and 7% from the Science faculty. Ground Zero has also been one of the NES events that has been able to have the most mentors for participants with over 50 speakers, mentors, and judges to guide our participants in various expertise areas.

**Comment by florentianayuwono** [comment]
@johnrhimawan for the pictures do we need to change as well? Can you suggest on how many to be displayed?
