### ISSUE TITLE
Update Sponsors Page

### ISSUE THREAD

**Issue by johnrhimawan** [NESGroundZero/groundzero-website#37]
Currently, the sponsors we have for Ground Zero are the following:

**The Patron**
Mapletree

**Diamond Sponsor**
HSBC

**Gold Sponsor**
SGInnovate

We are expecting AWS and NUS Enterprise to take on the role of Silver Sponsors but since they have not been confirmed we will put it aside for now.

**Comment by florentianayuwono** [comment]
@johnrhimawan for the sponsors logo do you have the provided image? or should I just google and paste from there?

**Comment by groundzero2023** [comment]
As a placeholder just use images found from Google, later we update with sponsors logo from their marketing and design teams
