### ISSUE TITLE
Resize Email Submission Form

### ISSUE THREAD

**Issue by johnrhimawan** [NESGroundZero/groundzero-website#42]
Currently, the size for the "Send us an email" page is quite small compared to the page. Let's resize it to fill up more of the page.

**Comment by groundzero2023** [comment]
Also direct all emails to `nesgroundzero@gmail.com`

**Comment by florentianayuwono** [comment]
@johnrhimawan by deprecated you mean we no longer need this?

**Comment by groundzero2023** [comment]
@florentianayuwono yup we're removing the feature for now
